DROP TABLE IF EXISTS memegen;
CREATE TABLE IF NOT EXISTS memegen (
	id text,
	name text,
	url text,
	width int,
	height int,
	box_count smallint,
  	PRIMARY KEY (id)
);

INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('87743020','Two Buttons','https://i.imgflip.com/1g8my4.jpg',600,908,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('131087935','Running Away Balloon','https://i.imgflip.com/261o3j.jpg',761,1024,5);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('247375501','Buff Doge vs. Cheems','https://i.imgflip.com/43a45p.png',937,720,4);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('222403160','Bernie I Am Once Again Asking For Your Support','https://i.imgflip.com/3oevdk.jpg',750,750,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('438680','Batman Slapping Robin','https://i.imgflip.com/9ehk.jpg',400,387,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('188390779','Woman Yelling At Cat','https://i.imgflip.com/345v97.jpg',680,438,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('1035805','Boardroom Meeting Suggestion','https://i.imgflip.com/m78d.jpg',500,649,4);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('119139145','Blank Nut Button','https://i.imgflip.com/1yxkcp.jpg',600,446,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('135256802','Epic Handshake','https://i.imgflip.com/28j0te.jpg',900,645,3);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('178591752','Tuxedo Winnie The Pooh','https://i.imgflip.com/2ybua0.png',800,582,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('97984','Disaster Girl','https://i.imgflip.com/23ls.jpg',500,375,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('114585149','Inhaling Seagull','https://i.imgflip.com/1w7ygt.jpg',1269,2825,4);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('259237855','Laughing Leo','https://i.imgflip.com/4acd7j.png',470,470,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('110163934','I Bet Hes Thinking About Other Women','https://i.imgflip.com/1tl71a.jpg',1654,930,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('91538330','X, X Everywhere','https://i.imgflip.com/1ihzfe.jpg',2118,1440,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('27813981','Hide the Pain Harold','https://i.imgflip.com/gk5el.jpg',480,601,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61579','One Does Not Simply','https://i.imgflip.com/1bij.jpg',568,335,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('89370399','Roll Safe Think About It','https://i.imgflip.com/1h7in3.jpg',702,395,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('135678846','Who Killed Hannibal','https://i.imgflip.com/28s2gu.jpg',1280,1440,3);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('175540452','Unsettled Tom','https://i.imgflip.com/2wifvo.jpg',680,550,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('91545132','Trump Bill Signing','https://i.imgflip.com/1ii4oc.jpg',1866,1529,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('132769734','Hard To Swallow Pills','https://i.imgflip.com/271ps6.jpg',680,979,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('161865971','Marked Safe From','https://i.imgflip.com/2odckz.jpg',618,499,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('196652226','Spongebob Ight Imma Head Out','https://i.imgflip.com/392xtu.jpg',822,960,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('6235864','Finding Neverland','https://i.imgflip.com/3pnmg.jpg',423,600,3);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('3218037','This Is Where Id Put My Trophy If I Had One','https://i.imgflip.com/1wz1x.jpg',300,418,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61556','Grandma Finds The Internet','https://i.imgflip.com/1bhw.jpg',640,480,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('101287','Third World Success Kid','https://i.imgflip.com/265j.jpg',500,500,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('101511','Dont You Squidward','https://i.imgflip.com/26br.jpg',500,333,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('216951317','Guy Holding Cardboard Sign','https://i.imgflip.com/3l60ph.jpg',700,702,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('99683372','Sleeping Shaq','https://i.imgflip.com/1nck6k.jpg',640,631,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('563423','That Would Be Great','https://i.imgflip.com/c2qn.jpg',526,440,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('29617627','Look At Me','https://i.imgflip.com/hmt3v.jpg',300,300,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61546','Brace Yourselves X is Coming','https://i.imgflip.com/1bhm.jpg',622,477,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('163573','Imagination Spongebob','https://i.imgflip.com/3i7p.jpg',500,366,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('157978092','Presidential Alert','https://i.imgflip.com/2m20oc.jpg',920,534,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('405658','Grumpy Cat','https://i.imgflip.com/8p0a.jpg',500,617,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('109765','Ill Just Wait Here','https://i.imgflip.com/2cp1.jpg',491,550,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61539','First World Problems','https://i.imgflip.com/1bhf.jpg',552,367,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('28034788','Marvel Civil War 1','https://i.imgflip.com/govs4.jpg',423,734,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('16464531','But Thats None Of My Business','https://i.imgflip.com/9sw43.jpg',600,600,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('101910402','Who Would Win?','https://i.imgflip.com/1ooaki.jpg',802,500,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('176908','Shut Up And Take My Money Fry','https://i.imgflip.com/3si4.jpg',500,281,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('235589','Evil Toddler','https://i.imgflip.com/51s5.jpg',500,332,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('27920','Surprised Koala','https://i.imgflip.com/ljk.jpg',500,667,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61582','Creepy Condescending Wonka','https://i.imgflip.com/1bim.jpg',550,545,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61581','Put It Somewhere Else Patrick','https://i.imgflip.com/1bil.jpg',343,604,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('53764','Peter Parker Cry','https://i.imgflip.com/15hg.jpg',400,992,4);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('14230520','Black Girl Wat','https://i.imgflip.com/8h0c8.jpg',599,626,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('112126428','Distracted Boyfriend','https://i.imgflip.com/1ur9b0.jpg',1200,800,3);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('129242436','Change My Mind','https://i.imgflip.com/24y43o.jpg',482,361,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('217743513','UNO Draw 25 Cards','https://i.imgflip.com/3lmzyx.jpg',500,494,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('124822590','Left Exit 12 Off Ramp','https://i.imgflip.com/22bdq6.jpg',804,767,3);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('102156234','Mocking Spongebob','https://i.imgflip.com/1otk96.jpg',502,353,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('93895088','Expanding Brain','https://i.imgflip.com/1jwhww.jpg',857,1202,4);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('131940431','Grus Plan','https://i.imgflip.com/26jxvz.jpg',700,449,4);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('252600902','Always Has Been','https://i.imgflip.com/46e43q.png',960,540,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('4087833','Waiting Skeleton','https://i.imgflip.com/2fm6x.jpg',298,403,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('148909805','Monkey Puppet','https://i.imgflip.com/2gnnjh.jpg',923,768,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('226297822','Panik Kalm Panik','https://i.imgflip.com/3qqcim.png',640,881,3);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('100777631','Is This A Pigeon','https://i.imgflip.com/1o00in.jpg',1587,1425,3);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('80707627','Sad Pablo Escobar','https://i.imgflip.com/1c1uej.jpg',720,709,3);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('123999232','The Scroll Of Truth','https://i.imgflip.com/21tqf4.jpg',1280,1236,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('155067746','Surprised Pikachu','https://i.imgflip.com/2kbn1e.jpg',1893,1893,3);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('180190441','Theyre The Same Picture','https://i.imgflip.com/2za3u1.jpg',1363,1524,3);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('101470','Ancient Aliens','https://i.imgflip.com/26am.jpg',500,437,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('195515965','Clown Applying Makeup','https://i.imgflip.com/38el31.jpg',750,798,4);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('134797956','American Chopper Argument','https://i.imgflip.com/2896ro.jpg',640,1800,5);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('124055727','Yall Got Any More Of That','https://i.imgflip.com/21uy0f.jpg',600,471,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('79132341','Bike Fall','https://i.imgflip.com/1b42wl.jpg',500,680,3);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('21735','The Rock Driving','https://i.imgflip.com/grr.jpg',568,700,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('5496396','Leonardo Dicaprio Cheers','https://i.imgflip.com/39t1o.jpg',600,400,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('55311130','This Is Fine','https://i.imgflip.com/wxica.jpg',580,282,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('28251713','Oprah You Get A','https://i.imgflip.com/gtj5t.jpg',620,465,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('8072285','Doge','https://i.imgflip.com/4t0m5.jpg',620,620,5);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('84341851','Evil Kermit','https://i.imgflip.com/1e7ql7.jpg',700,325,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('14371066','Star Wars Yoda','https://i.imgflip.com/8k0sa.jpg',620,714,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61520','Futurama Fry','https://i.imgflip.com/1bgw.jpg',552,414,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('101288','Third World Skeptical Kid','https://i.imgflip.com/265k.jpg',426,426,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61532','The Most Interesting Man In The World','https://i.imgflip.com/1bh8.jpg',550,690,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('4173692','Scared Cat','https://i.imgflip.com/2hgfw.jpg',620,464,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('460541','Jack Sparrow Being Chased','https://i.imgflip.com/9vct.jpg',500,375,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('285870','Squidward','https://i.imgflip.com/64ku.jpg',500,750,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61544','Success Kid','https://i.imgflip.com/1bhk.jpg',500,500,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('6531067','See Nobody Cares','https://i.imgflip.com/3vzej.jpg',620,676,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61585','Bad Luck Brian','https://i.imgflip.com/1bip.jpg',475,562,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61533','X All The Y','https://i.imgflip.com/1bh9.jpg',500,355,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('29562797','Im The Captain Now','https://i.imgflip.com/hlmst.jpg',478,350,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('8279814','Cute Cat','https://i.imgflip.com/4xgqu.jpg',480,532,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('21604248','Mugatu So Hot Right Now','https://i.imgflip.com/cv1y0.jpg',620,497,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('89655','Uncle Sam','https://i.imgflip.com/1x6f.jpg',620,833,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61580','Too Damn High','https://i.imgflip.com/1bik.jpg',420,316,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('1202623','Keep Calm And Carry On Red','https://i.imgflip.com/pry7.jpg',500,704,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('61527','Y U No','https://i.imgflip.com/1bh3.jpg',500,500,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('40945639','Dr Evil Laser','https://i.imgflip.com/odluv.jpg',500,405,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('101716','Yo Dawg Heard You','https://i.imgflip.com/26hg.jpg',500,323,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('71428573','Say it Again, Dexter','https://i.imgflip.com/16iyn1.jpg',698,900,2);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('56225174','Be Like Bill','https://i.imgflip.com/xh3me.jpg',913,907,4);
INSERT INTO memegen(id,name,url,width,height,box_count) VALUES('922147','Laughing Men In Suits','https://i.imgflip.com/jrj7.jpg',500,333,2);


DROP TABLE IF EXISTS memes_saved;
CREATE TABLE IF NOT EXISTS memes_saved (
    uuid uuid,
	id text,
	sessionid uuid,
	name text,
	url text,
	toptext text,
	bottomtext text,
	memename text,
	width int,
	height int,
	box_count smallint,
	image_source text,
  	PRIMARY KEY (uuid)
);
CREATE CUSTOM INDEX memes_saved_id_idx ON memes_saved (id) USING 'StorageAttachedIndex' WITH OPTIONS = {'normalize': 'true', 'case_sensitive': 'false'};
